version: '3.8'

services:
  # Frontend React
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - WDS_SOCKET_PORT=443
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - acces-services-network

  # Backend FastAPI
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=acces_services_db
      - CORS_ORIGINS=http://localhost:3000,https://your-domain.com
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    networks:
      - acces-services-network

  # Base de données MongoDB
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=acces_services_db
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - acces-services-network

volumes:
  mongodb_data:

networks:
  acces-services-network:
    driver: bridge